### ISSUE TITLE
Don't mess with builtin

### ISSUE THREAD

**Issue by Suor** [rfk/magicsuper#1]
Wouldn't it be cleaner to just provide magic super as drop-in replacement instead of taking it into builtins? Then you just do

``` python
from magicsuper import super
# or even
from magicsuper import super as superm
```

in your module and don't interfere with any 3rd party modules.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
